import { DiseaseInfo, Language, Scheme, UserProfile } from '../types';

// SCHEMES & INSURANCE DATABASE
export const SCHEMES: Scheme[] = [
  {
    id: 'pm_kisan',
    name: {
      [Language.EN]: 'PM-KISAN Samman Nidhi',
      [Language.HI]: 'पीएम-किसान सम्मान निधि',
      [Language.TA]: 'பிஎம்-கிசான் சம்மன் நிதி',
      [Language.TE]: 'PM-కిసాన్ సమ్మాన్ నిధి',
      [Language.ML]: 'പിഎം-കിസാൻ സമ്മാൻ നിധി',
      [Language.KN]: 'ಪಿಎಂ-ಕಿಸಾನ್ ಸಮ್ಮಾನ್ ನಿಧಿ',
      [Language.MR]: 'पीएम-किसान सन्मान निधी'
    },
    description: {
      [Language.EN]: 'Financial support of ₹6,000 per year for small farmers.',
      [Language.HI]: 'छोटे किसानों के लिए प्रति वर्ष ₹6,000 की वित्तीय सहायता।',
      [Language.TA]: 'சிறு விவசாயிகளுக்கு ஆண்டுக்கு ₹6,000 நிதியுதவி.',
      [Language.TE]: 'చిన్న రైతులకు సంవత్సరానికి ₹6,000 ఆర్థిక సహాయం.',
      [Language.ML]: 'ചെറുകിട കർഷകർക്ക് പ്രതിവർഷം ₹6,000 ധനസഹായം.',
      [Language.KN]: 'ಸಣ್ಣ ರೈತರಿಗೆ ವರ್ಷಕ್ಕೆ ₹6,000 ಆರ್ಥಿಕ ನೆರವು.',
      [Language.MR]: 'अल्पभूधारक शेतकऱ्यांसाठी वर्षाला ₹६,००० ची आर्थिक मदत.'
    },
    benefits: {
      [Language.EN]: 'Direct bank transfer in 3 installments.',
      [Language.HI]: '3 किस्तों में सीधा बैंक हस्तांतरण।',
      [Language.TA]: '3 தவணைகளில் நேரடி வங்கி பரிமாற்றம்.',
      [Language.TE]: '3 వాయిదాలలో నేరుగా బ్యాంకు బదిలీ.',
      [Language.ML]: '3 ഗഡുക്കളായി നേരിട്ടുള്ള ബാങ്ക് കൈമാറ്റം.',
      [Language.KN]: '3 ಕಂತುಗಳಲ್ಲಿ ನೇರ ಬ್ಯಾಂಕ್ ವರ್ಗಾವಣೆ.',
      [Language.MR]: '३ हप्त्यांमध्ये थेट बँक हस्तांतरण.'
    },
    eligibilityRule: (user: UserProfile) => user.farmSizeAcres <= 5 // Approx 2 hectares
  },
  {
    id: 'pmfby',
    name: {
      [Language.EN]: 'PMFBY Crop Insurance',
      [Language.HI]: 'प्रधानमंत्री फसल बीमा योजना',
      [Language.TA]: 'பிரதம மந்திரி பயிர் காப்பீடு',
      [Language.TE]: 'ప్రధాన మంత్రి ఫసల్ బీమా యోజన',
      [Language.ML]: 'പ്രധാനമന്ത്രി ഫസൽ ബീമാ യോജന',
      [Language.KN]: 'ಪ್ರಧಾನ ಮಂತ್ರಿ ಫಸಲ್ ಬಿಮಾ ಯೋಜನೆ',
      [Language.MR]: 'प्रधानमंत्री पीक विमा योजना'
    },
    description: {
      [Language.EN]: 'Insurance coverage for crop loss due to natural calamities.',
      [Language.HI]: 'प्राकृतिक आपदाओं के कारण फसल के नुकसान के लिए बीमा कवर।',
      [Language.TA]: 'இயற்கை சீற்றங்களால் ஏற்படும் பயிர் இழப்புக்கு காப்பீடு.',
      [Language.TE]: 'ప్రకృతి వైపరీత్యాల వల్ల పంట నష్టానికి బీమా రక్షణ.',
      [Language.ML]: 'പ്രകൃതിദുരന്തങ്ങൾ മൂലമുള്ള വിളനാശത്തിന് ഇൻഷുറൻസ് പരിരക്ഷ.',
      [Language.KN]: 'ನೈಸರ್ಗಿಕ ವಿಕೋಪಗಳಿಂದ ಬೆಳೆ ಹಾನಿಗೆ ವಿಮೆ ರಕ್ಷಣೆ.',
      [Language.MR]: 'नैसर्गिक आपत्तींमुळे पिकाच्या नुकसानीसाठी विमा संरक्षण.'
    },
    benefits: {
      [Language.EN]: 'Low premium (2% Kharif, 1.5% Rabi). Full claim settlement.',
      [Language.HI]: 'कम प्रीमियम (2% खरीफ, 1.5% रबी)। पूर्ण दावा निपटान।',
      [Language.TA]: 'குறைந்த பிரீமியம். முழுமையான இழப்பீடு.',
      [Language.TE]: 'తక్కువ ప్రీమియం. పూర్తి క్లెయిమ్ సెటిల్మెంట్.',
      [Language.ML]: 'കുറഞ്ഞ പ്രീമിയം. മുഴുവൻ ക്ലെയിം സെറ്റിൽമെന്റ്.',
      [Language.KN]: 'ಕಡಿಮೆ ಪ್ರೀಮಿಯಂ. ಪೂರ್ಣ ಕ್ಲೈಮ್ ಇತ್ಯರ್ಥ.',
      [Language.MR]: 'कमी हप्ता. पूर्ण दावा पूर्तता.'
    },
    eligibilityRule: (user: UserProfile) => true // All farmers eligible
  },
  {
    id: 'shc',
    name: {
      [Language.EN]: 'Soil Health Card',
      [Language.HI]: 'मृदा स्वास्थ्य कार्ड',
      [Language.TA]: 'மண் வள அட்டை',
      [Language.TE]: 'సాయిల్ హెల్త్ కార్డ్',
      [Language.ML]: 'സോയിൽ ഹെൽത്ത് കാർഡ്',
      [Language.KN]: 'ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್',
      [Language.MR]: 'मृदा आरोग्य कार्ड'
    },
    description: {
      [Language.EN]: 'Get soil nutrient status and fertilizer recommendations.',
      [Language.HI]: 'मिट्टी के पोषक तत्वों की स्थिति और उर्वरक सिफारिशें प्राप्त करें।',
      [Language.TA]: 'மண் ஊட்டச்சத்து நிலை மற்றும் உர பரிந்துரைகளைப் பெறுங்கள்.',
      [Language.TE]: 'మట్టి పోషకాల స్థితి మరియు ఎరువుల సిఫార్సులను పొందండి.',
      [Language.ML]: 'മണ്ണിലെ പോഷക നിലയും വളം ശുപാർശകളും നേടുക.',
      [Language.KN]: 'ಮಣ್ಣಿನ ಪೋಷಕಾಂಶ ಸ್ಥಿತಿ ಮತ್ತು ರಸಗೊಬ್ಬರ ಶಿಫಾರಸುಗಳನ್ನು ಪಡೆಯಿರಿ.',
      [Language.MR]: 'मातीतील पोषक तत्वांची स्थिती आणि खतांच्या शिफारशी मिळवा.'
    },
    benefits: {
      [Language.EN]: 'Optimized yield and reduced fertilizer cost.',
      [Language.HI]: 'बेहतर उपज और कम उर्वरक लागत।',
      [Language.TA]: 'சிறந்த மகசூல் மற்றும் குறைந்த உரச் செலவு.',
      [Language.TE]: 'మెరుగైన దిగుబడి మరియు తగ్గిన ఎరువుల ఖర్చు.',
      [Language.ML]: 'മെച്ചപ്പെട്ട വിളവും കുറഞ്ഞ വളം ചെലവും.',
      [Language.KN]: 'ಉತ್ತಮ ಇಳುವರಿ ಮತ್ತು ಕಡಿಮೆ ರಸಗೊಬ್ಬರ ವೆಚ್ಚ.',
      [Language.MR]: 'चांगले उत्पन्न आणि खतांचा कमी खर्च.'
    },
    eligibilityRule: (user: UserProfile) => true
  }
];

export const DISEASES: Record<string, DiseaseInfo> = {
  'tomato_early_blight': {
    id: 'tomato_early_blight',
    name: {
      [Language.EN]: 'Tomato Early Blight',
      [Language.HI]: 'टमाटर का अगेती झुलसा',
      [Language.TA]: 'தக்காளி முன் கருகல் நோய்',
      [Language.TE]: 'టమాటో ఎర్లీ బ్లైట్',
      [Language.ML]: 'തക്കാളി നേരത്തെയുള്ള ബ്ലൈറ്റ്',
      [Language.KN]: 'ಟೊಮೆಟೊ ಅರ್ಲಿ ಬ್ಲೈಟ್',
      [Language.MR]: 'टोमॅटो अर्ली ब्लाईट'
    },
    description: {
      [Language.EN]: 'A fungal disease that causes concentric rings on older leaves.',
      [Language.HI]: 'एक कवक रोग जो पुरानी पत्तियों पर संकेंद्रित छल्ले का कारण बनता है।',
      [Language.TA]: 'பழைய இலைகளில் வட்ட வளையங்களை ஏற்படுத்தும் பூஞ்சை நோய்.',
      [Language.TE]: 'పాత ఆకులపై వలయాలను కలిగించే ఫంగల్ వ్యాధి.',
      [Language.ML]: 'പഴയ ഇലകളിൽ വളയങ്ങൾ ഉണ്ടാക്കുന്ന ഫംഗസ് രോഗം.',
      [Language.KN]: 'ಹಳೆಯ ಎಲೆಗಳ ಮೇಲೆ ಉಂಗುರಗಳನ್ನು ಉಂಟುಮಾಡುವ ಶಿಲೀಂಧ್ರ ರೋಗ.',
      [Language.MR]: 'जुन्या पानांवर गोलाकार डाग पाडणारा बुरशीजन्य रोग.'
    },
    treatment: {
      do: {
        [Language.EN]: ['Remove infected leaves immediately', 'Apply copper-based fungicide'],
        [Language.HI]: ['संक्रमित पत्तियों को तुरंत हटा दें', 'तांबे आधारित कवकनाशी का प्रयोग करें'],
        [Language.TA]: ['பாதிக்கப்பட்ட இலைகளை உடனடியாக அகற்றவும்', 'செம்பு கலந்த பூஞ்சைக் கொல்லியைப் பயன்படுத்தவும்'],
        [Language.TE]: ['వ్యాధి సోకిన ఆకులను వెంటనే తొలగించండి', 'రాగి ఆధారిత శిలీంద్ర  వాడండి'],
        [Language.ML]: ['രോഗം ബാധിച്ച ഇലകൾ ഉടൻ നീക്കം ചെയ്യുക', 'കോപ്പർ അധിഷ്ഠിത കുമിൾനാശിനി പ്രയോഗിക്കുക'],
        [Language.KN]: ['ಸೋಂಕಿತ ಎಲೆಗಳನ್ನು ತಕ್ಷಣ ತೆಗೆದುಹಾಕಿ', 'ತಾಮ್ರ ಆಧಾರಿತ ಶಿಲೀಂಧ್ರನಾಶಕವನ್ನು ಬಳಸಿ'],
        [Language.MR]: ['संसर्ग झालेली पाने त्वरित काढून टाका', 'तांबे युक्त बुरशीनाशक वापरा']
      },
      dont: {
        [Language.EN]: ['Do not water from overhead'],
        [Language.HI]: ['ऊपर से पानी न दें'],
        [Language.TA]: ['மேலே இருந்து தண்ணீர் ஊற்ற வேண்டாம்'],
        [Language.TE]: ['పై నుండి నీరు పోయవద్దు'],
        [Language.ML]: ['മുകളിൽ നിന്ന് നനയ്ക്കരുത്'],
        [Language.KN]: ['ಮೇಲಿನಿಂದ ನೀರು ಹಾಕಬೇಡಿ'],
        [Language.MR]: ['वरून पाणी देऊ नका']
      }
    }
  },
  'potato_late_blight': {
    id: 'potato_late_blight',
    name: {
      [Language.EN]: 'Potato Late Blight',
      [Language.HI]: 'आलू का पछेती झुलसा',
      [Language.TA]: 'உருளைக்கிழங்கு பின் கருகல் நோய்',
      [Language.TE]: 'బంగాళాదుంప లేట్ బ్లైట్',
      [Language.ML]: 'ഉരുളക്കിഴങ്ങ് ലേറ്റ് ബ്ലൈറ്റ്',
      [Language.KN]: 'ಆಲೂಗಡ್ಡೆ ಲೇಟ್ ಬ್ಲೈಟ್',
      [Language.MR]: 'बटाटा उशिरा ब्लाईट'
    },
    description: {
      [Language.EN]: 'Water-soaked lesions on leaves.',
      [Language.HI]: 'पत्तियों पर पानी से लथपथ घाव।',
      [Language.TA]: 'இலைகளில் நீர் ஊறிய காயங்கள்.',
      [Language.TE]: 'ఆకులపై నీటితో తడిసిన మచ్చలు.',
      [Language.ML]: 'ഇലകളിൽ വെള്ളം നനഞ്ഞ പാടുകൾ.',
      [Language.KN]: 'ಎಲೆಗಳ ಮೇಲೆ ನೀರಿನಿಂದ ನೆನೆದ ಕಲೆಗಳು.',
      [Language.MR]: 'पानांवर पाण्याने भरलेले डाग.'
    },
    treatment: {
      do: {
        [Language.EN]: ['Spray Mancozeb proactively'],
        [Language.HI]: ['मैनकोजेब का छिड़काव करें'],
        [Language.TA]: ['முன்னெச்சரிக்கையாக மான்கோசெப் தெளிக்கவும்'],
        [Language.TE]: ['ముందుగానే మాంకోజెబ్ పిచికారీ చేయండి'],
        [Language.ML]: ['മുൻകൂട്ടി മാങ്കോസെബ് തളിക്കുക'],
        [Language.KN]: ['ಮುನ್ನೆಚ್ಚರಿಕೆಯಾಗಿ ಮ್ಯಾಂಕೋಜೆಬ್ ಸಿಂಪಡಿಸಿ'],
        [Language.MR]: ['मँकोझेबची फवारणी करा']
      },
      dont: {
        [Language.EN]: ['Do not leave infected tubers'],
        [Language.HI]: ['संक्रमित कंद न छोड़ें'],
        [Language.TA]: ['பாதிக்கப்பட்ட கிழங்குகளை விட வேண்டாம்'],
        [Language.TE]: ['వ్యాధి సోకిన దుంపలను వదలవద్దు'],
        [Language.ML]: ['രോഗം ബാധിച്ച കിഴങ്ങുകൾ ഉപേക്ഷിക്കരുത്'],
        [Language.KN]: ['ಸೋಂಕಿತ ಗೆಡ್ಡೆಗಳನ್ನು ಬಿಡಬೇಡಿ'],
        [Language.MR]: ['संसर्ग झालेले बटाटे शेतात सोडू नका']
      }
    }
  }
};

export const UI_TEXT = {
  [Language.EN]: {
    welcome: "Welcome",
    tapToSpeak: "Tap to Speak",
    register: "Farmer Registration",
    name: "Full Name",
    phone: "Mobile Number",
    location: "Village / District",
    crop: "Primary Crop",
    acres: "Farm Size (Acres)",
    submit: "Save Profile",
    detect: "Detect Disease",
    weather: "Weather & Alerts",
    yield: "Yield Prediction",
    community: "Community Reports",
    soilHealth: "Soil Health",
    topCrop: "Top Crop",
    inputAdvisor: "Input Advisor",
    schemes: "Govt Schemes",
    alert: "ALERT",
    safe: "Safe",
    loading: "Thinking...",
    takePhoto: "Take Photo / Upload",
    analyzing: "Analyzing Leaf...",
    treatment: "Treatment Advice",
    do: "DO",
    dont: "DON'T",
    share: "Share with Community",
    shared: "Report Shared",
    voiceFallback: "Please type your details.",
    yieldCalc: "Calculate Yield",
    factors: "Key Factors",
    soilAnalysis: "Soil Analysis",
    phLevel: "pH Level",
    nitrogen: "Nitrogen",
    phosphorus: "Phosphorus",
    potassium: "Potassium",
    organicCarbon: "Organic Carbon",
    texture: "Texture",
    recommendation: "Best Crop for You",
    whyThisCrop: "Why this crop?",
    acidic: "Acidic",
    neutral: "Neutral",
    alkaline: "Alkaline",
    low: "Low",
    medium: "Medium",
    high: "High",
    sandy: "Sandy",
    loamy: "Loamy",
    clay: "Clay",
    safeToSpray: "Safe to Spray",
    dontSpray: "Do Not Spray",
    rainWarning: "Rain Expected. Fertilizer will wash away.",
    windWarning: "High Wind. Pesticide will drift.",
    perfectDay: "Conditions are perfect for inputs.",
    eligibleSchemes: "Eligible Schemes",
    checkEligibility: "Checking Eligibility...",
    soilStatus: "Soil Status",
    healthy: "Healthy",
    needsCare: "Needs Attention",
    fertilizerAdvice: "Fertilizer Advice",
    tips: "Important Tips",
    reduceNitrogen: "Reduce nitrogen fertilizer (Urea).",
    addPotash: "Add Potash (MOP) for better fruiting.",
    addPhosphorus: "Add Phosphorus (DAP) for root growth.",
    addCompost: "Add Organic Compost.",
    waterFreq: "Sandy soil needs frequent watering.",
    drainage: "Ensure drainage, avoid waterlogging.",
    soilSummary: "Your soil",
    is: "is",
    and: "and",
    marketPrice: "Market Price",
    sellNow: "Sell Now",
    wait: "Wait",
    farmHistory: "Farm Record Book",
    pastRecords: "Past Crop Records",
    profit: "Profit",
    loss: "Loss",
    aiInsight: "AI Insight",
    historyWarning: "Last time, this crop had disease issues.",
    preventiveAction: "Take preventive measures early this season.",
    priceUp: "Price is higher than last week.",
    priceDown: "Price has dropped recently.",
    cropGrowth: "Crop Growth",
    currentStage: "Current Stage",
    cropAge: "Crop Age",
    days: "days",
    financialAdvice: "Cost Advice",
    invested: "Invested",
    risk: "Risk",
    myCropStatus: "My Crop Status",
    seedling: "Seedling",
    vegetative: "Vegetative",
    flowering: "Flowering",
    fruiting: "Fruiting",
    harvest: "Harvest",
    uploadReport: "Upload Soil Report",
    govtCard: "Get Govt Soil Health Card",
    analyzingReport: "Reading Soil Report...",
    verified: "Verified by Lab Report",
    estimated: "Satellite Estimate",
    getFreeTest: "Get Free Soil Test",
    govtShcHelp: "Visit nearest Agriculture Office with soil sample. Get report in 14 days.",
    sustainable: "Sustainable Farming",
    mulching: "Mulching",
    cropRotation: "Crop Rotation",
    waterMgmt: "Water Mgmt",
    profile: "My Profile",
    logout: "Logout",
    help: "Assistant Help",
    irrigation: "Irrigation Type",
    soilType: "Soil Type",
    farmingExp: "Experience (Years)",
    tubeWell: "Tube Well",
    canal: "Canal",
    rainFed: "Rainfed",
    drip: "Drip",
    blackSoil: "Black Soil",
    redSoil: "Red Soil"
  },
  [Language.HI]: {
    welcome: "स्वागत है",
    tapToSpeak: "बोलने के लिए दबाएं",
    register: "किसान पंजीकरण",
    name: "पूरा नाम",
    phone: "मोबाइल नंबर",
    location: "गाँव / जिला",
    crop: "मुख्य फसल",
    acres: "खेत का आकार (एकड़)",
    submit: "प्रोफ़ाइल सहेजें",
    detect: "रोग का पता लगाएं",
    weather: "मौसम और चेतावनी",
    yield: "उपज की भविष्यवाणी",
    community: "सामुदायिक रिपोर्ट",
    soilHealth: "मृदा स्वास्थ्य",
    topCrop: "सर्वोत्तम फसल",
    inputAdvisor: "इनपुट सलाहकार",
    schemes: "सरकारी योजनाएं",
    alert: "चेतावनी",
    safe: "सुरक्षित",
    loading: "सोच रहा हूँ...",
    takePhoto: "फोटो लें / अपलोड करें",
    analyzing: "पत्ती की जाँच हो रही है...",
    treatment: "उपचार सलाह",
    do: "करें",
    dont: "न करें",
    share: "समुदाय के साथ साझा करें",
    shared: "रिपोर्ट साझा की गई",
    voiceFallback: "कृपया अपना विवरण टाइप करें।",
    yieldCalc: "उपज की गणना करें",
    factors: "प्रमुख कारक",
    soilAnalysis: "मृदा विश्लेषण",
    phLevel: "pH स्तर",
    nitrogen: "नाइट्रोजन",
    phosphorus: "फास्फोरस",
    potassium: "पोटाश",
    organicCarbon: "जैविक कार्बन",
    texture: "बनावट",
    recommendation: "आपके लिए सर्वोत्तम फसल",
    whyThisCrop: "यह फसल क्यों?",
    acidic: "अम्लीय",
    neutral: "तटस्थ",
    alkaline: "क्षारीय",
    low: "कम",
    medium: "मध्यम",
    high: "अधिक",
    sandy: "रेतीली",
    loamy: "दोमट",
    clay: "चिकनी",
    safeToSpray: "छिड़काव के लिए सुरक्षित",
    dontSpray: "छिड़काव न करें",
    rainWarning: "बारिश की उम्मीद है। खाद बह जाएगी।",
    windWarning: "तेज हवा। कीटनाशक उड़ जाएगा।",
    perfectDay: "इनपुट के लिए स्थितियां उत्तम हैं।",
    eligibleSchemes: "पात्र योजनाएं",
    checkEligibility: "पात्रता की जाँच हो रही है...",
    soilStatus: "मृदा स्थिति",
    healthy: "स्वस्थ",
    needsCare: "ध्यान देने की आवश्यकता",
    fertilizerAdvice: "खाद सलाह",
    tips: "महत्वपूर्ण सुझाव",
    reduceNitrogen: "यूरिया का प्रयोग कम करें।",
    addPotash: "फलों के लिए पोटाश डालें।",
    addPhosphorus: "जड़ों के लिए फास्फोरस डालें।",
    addCompost: "जैविक खाद डालें।",
    waterFreq: "रेतीली मिट्टी को बार-बार पानी चाहिए।",
    drainage: "जल निकासी सुनिश्चित करें।",
    soilSummary: "आपकी मिट्टी",
    is: "है",
    and: "और",
    marketPrice: "बाजार भाव",
    sellNow: "अभी बेचें",
    wait: "रुकें",
    farmHistory: "खेत रिकॉर्ड बुक",
    pastRecords: "पिछली फसल का रिकॉर्ड",
    profit: "लाभ",
    loss: "हानि",
    aiInsight: "एआई सुझाव",
    historyWarning: "पिछली बार, इस फसल में बीमारी की समस्या थी।",
    preventiveAction: "इस सीजन में पहले से निवारक उपाय करें।",
    priceUp: "कीमत पिछले हफ्ते से ज्यादा है।",
    priceDown: "हाल ही में कीमत गिरी है।",
    cropGrowth: "फसल विकास",
    currentStage: "वर्तमान चरण",
    cropAge: "फसल की उम्र",
    days: "दिन",
    financialAdvice: "लागत सलाह",
    invested: "निवेश किया",
    risk: "जोखिम",
    myCropStatus: "मेरी फसल की स्थिति",
    seedling: "अंकुर",
    vegetative: "वानस्पतिक",
    flowering: "फूल आना",
    fruiting: "फल आना",
    harvest: "कटाई",
    uploadReport: "मृदा रिपोर्ट अपलोड करें",
    govtCard: "सरकारी मृदा स्वास्थ्य कार्ड प्राप्त करें",
    analyzingReport: "रिपोर्ट पढ़ी जा रही है...",
    verified: "लैब रिपोर्ट द्वारा सत्यापित",
    estimated: "उपग्रह अनुमान",
    getFreeTest: "मुफ्त मिट्टी परीक्षण प्राप्त करें",
    govtShcHelp: "निकटतम कृषि कार्यालय में मिट्टी का नमूना दें। 14 दिनों में रिपोर्ट प्राप्त करें।",
    sustainable: "टिकाऊ खेती",
    mulching: "मल्चिंग",
    cropRotation: "फसल चक्र",
    waterMgmt: "जल प्रबंधन",
    profile: "मेरी प्रोफ़ाइल",
    logout: "लॉग आउट",
    help: "सहायता",
    irrigation: "सिंचाई का प्रकार",
    soilType: "मिट्टी का प्रकार",
    farmingExp: "अनुभव (वर्ष)",
    tubeWell: "ट्यूब वेल",
    canal: "नहर",
    rainFed: "वर्षा आधारित",
    drip: "ड्रिप",
    blackSoil: "काली मिट्टी",
    redSoil: "लाल मिट्टी"
  },
  [Language.TA]: {
    welcome: "வணக்கம்",
    tapToSpeak: "பேச தட்டவும்",
    register: "விவசாயி பதிவு",
    name: "முழு பெயர்",
    phone: "மொபைல் எண்",
    location: "கிராமம் / மாவட்டம்",
    crop: "முதன்மையான பயிர்",
    acres: "பண்ணை அளவு (ஏக்கர்)",
    submit: "சுயவிவரத்தைச் சேமி",
    detect: "நோய் கண்டறிதல்",
    weather: "வானிலை & எச்சரிக்கைகள்",
    yield: "மகசூல் கணிப்பு",
    community: "சமூக அறிக்கைகள்",
    soilHealth: "மண் வளம்",
    topCrop: "சிறந்த பயிர்",
    inputAdvisor: "உள்ளீட்டு ஆலோசகர்",
    schemes: "அரசு திட்டங்கள்",
    alert: "எச்சரிக்கை",
    safe: "பாதுகாப்பானது",
    loading: "யோசிக்கிறேன்...",
    takePhoto: "புகைப்படம் எடு / பதிவேற்று",
    analyzing: "இலையை ஆய்வு செய்கிறது...",
    treatment: "சிகிச்சை ஆலோசனை",
    do: "செய்யவும்",
    dont: "செய்ய வேண்டாம்",
    share: "சமூகத்துடன் பகிரவும்",
    shared: "அறிக்கை பகிரப்பட்டது",
    voiceFallback: "உங்கள் விவரங்களைப் பதிவு செய்யவும்.",
    yieldCalc: "மகசூல் கணக்கிடு",
    factors: "முக்கிய காரணிகள்",
    soilAnalysis: "மண் ஆய்வு",
    phLevel: "pH நிலை",
    nitrogen: "நைட்ரஜன்",
    phosphorus: "பாஸ்பரஸ்",
    potassium: "பொட்டாசியம்",
    organicCarbon: "கரிம கார்பன்",
    texture: "கட்டமைப்பு",
    recommendation: "உங்களுக்கான சிறந்த பயிர்",
    whyThisCrop: "ஏன் இந்த பயிர்?",
    acidic: "அமிலம்",
    neutral: "நடுநிலை",
    alkaline: "காரத்தன்மை",
    low: "குறைவு",
    medium: "நடுத்தரம்",
    high: "அதிகம்",
    sandy: "மணல்",
    loamy: "வண்டல்",
    clay: "களிமண்",
    safeToSpray: "தெளிக்க பாதுகாப்பானது",
    dontSpray: "தெளிக்க வேண்டாம்",
    rainWarning: "மழை எதிர்பார்க்கப்படுகிறது. உரம் அடித்துச் செல்லப்படும்.",
    windWarning: "அதிக காற்று. பூச்சிக்கொல்லி வீணாகும்.",
    perfectDay: "உள்ளீடுகளுக்கு வானிலை மிகச் சரியாக உள்ளது.",
    eligibleSchemes: "தகுதியான திட்டங்கள்",
    checkEligibility: "தகுதியை சரிபார்க்கிறது...",
    soilStatus: "மண் நிலை",
    healthy: "ஆரோக்கியமானது",
    needsCare: "கவனம் தேவை",
    fertilizerAdvice: "உர ஆலோசனை",
    tips: "முக்கிய குறிப்புகள்",
    reduceNitrogen: "யூரியாவைக் குறைக்கவும்.",
    addPotash: "பொட்டாஷ் சேர்க்கவும்.",
    addPhosphorus: "பாஸ்பரஸ் சேர்க்கவும்.",
    addCompost: "இயற்கை உரம் சேர்க்கவும்.",
    waterFreq: "மணல் மண்ணுக்கு அடிக்கடி நீர் பாய்ச்ச வேண்டும்.",
    drainage: "வடிகால் வசதியை உறுதி செய்யவும்.",
    soilSummary: "உங்கள் மண்",
    is: "உள்ளது",
    and: "மற்றும்",
    marketPrice: "சந்தை விலை",
    sellNow: "இப்போது விற்கவும்",
    wait: "காத்திருங்கள்",
    farmHistory: "பண்ணை பதிவு புத்தகம்",
    pastRecords: "கடந்த பயிர் பதிவுகள்",
    profit: "லாபம்",
    loss: "நஷ்டம்",
    aiInsight: "AI நுண்ணறிவு",
    historyWarning: "கடந்த முறை, இந்த பயிரில் நோய் பாதிப்பு இருந்தது.",
    preventiveAction: "இந்த பருவத்தில் முன்னெச்சரிக்கை நடவடிக்கைகளை மேற்கொள்ளுங்கள்.",
    priceUp: "விலை கடந்த வாரத்தை விட அதிகமாக உள்ளது.",
    priceDown: "சமீபத்தில் விலை குறைந்துள்ளது.",
    cropGrowth: "பயிர் வளர்ச்சி",
    currentStage: "தற்போதைய நிலை",
    cropAge: "பயிர் வயது",
    days: "நாட்கள்",
    financialAdvice: "செலவு ஆலோசனை",
    invested: "முதலீடு",
    risk: "ஆபத்து",
    myCropStatus: "என் பயிர் நிலை",
    seedling: "நாற்று",
    vegetative: "வளர்ச்சி",
    flowering: "பூக்கும்",
    fruiting: "காய்க்கும்",
    harvest: "அறுவடை",
    uploadReport: "மண் அறிக்கை பதிவேற்றம்",
    govtCard: "மண் வள அட்டை பெறுங்கள்",
    analyzingReport: "அறிக்கையை ஆய்வு செய்கிறது...",
    verified: "ஆய்வக அறிக்கையால் சரிபார்க்கப்பட்டது",
    estimated: "செயற்கைக்கோள் கணிப்பு",
    getFreeTest: "இலவச மண் பரிசோதனை பெறுங்கள்",
    govtShcHelp: "மண் மாதிரியுடன் அருகிலுள்ள வேளாண்மை அலுவலகத்திற்குச் செல்லவும். 14 நாட்களில் அறிக்கை கிடைக்கும்.",
    sustainable: "நீடித்த விவசாயம்",
    mulching: "மூடாக்கு",
    cropRotation: "பயிர் சுழற்சி",
    waterMgmt: "நீர் மேலாண்மை",
    profile: "என் சுயவிவரம்",
    logout: "வெளியேறு",
    help: "உதவி",
    irrigation: "நீர்ப்பாசன வகை",
    soilType: "மண் வகை",
    farmingExp: "அனுபவம் (ஆண்டுகள்)",
    tubeWell: "ஆழ்துளை கிணறு",
    canal: "கால்வாய்",
    rainFed: "மானாவாரி",
    drip: "சொட்டு நீர்",
    blackSoil: "கரிசல் மண்",
    redSoil: "செம்மண்"
  },
  [Language.TE]: {
    welcome: "స్వాగతం",
    tapToSpeak: "మాట్లాడటానికి నొక్కండి",
    register: "రైతు నమోదు",
    name: "పూర్తి పేరు",
    phone: "మొబైల్ సంఖ్య",
    location: "గ్రామం / జిల్లా",
    crop: "ప్రధాన పంట",
    acres: "పొలం పరిమాణం (ఎకరాలు)",
    submit: "ప్రొఫైల్ సేవ్ చేయండి",
    detect: "వ్యాధి గుర్తింపు",
    weather: "వాతావరణం & హెచ్చరికలు",
    yield: "దిగుబడి అంచనా",
    community: "కమ్యూనిటీ నివేదికలు",
    soilHealth: "నేల ఆరోగ్యం",
    topCrop: "ఉత్తమ పంట",
    inputAdvisor: "ఇన్పుట్ సలహాదారు",
    schemes: "ప్రభుత్వ పథకాలు",
    alert: "హెచ్చరిక",
    safe: "సురక్షితం",
    loading: "ఆలోచిస్తున్నాను...",
    takePhoto: "ఫోటో తీయండి / అప్‌లోడ్ చేయండి",
    analyzing: "ఆకును విశ్లేషిస్తోంది...",
    treatment: "చికిత్స సలహా",
    do: "చేయండి",
    dont: "చేయవద్దు",
    share: "కమ్యూనిటీతో పంచుకోండి",
    shared: "నివేదిక భాగస్వామ్యం చేయబడింది",
    voiceFallback: "దయచేసి మీ వివరాలను టైప్ చేయండి.",
    yieldCalc: "దిగుబడిని లెక్కించండి",
    factors: "ముఖ్య అంశాలు",
    soilAnalysis: "నేల విశ్లేషణ",
    phLevel: "pH స్థాయి",
    nitrogen: "నైట్రోజన్",
    phosphorus: "ఫాస్పరస్",
    potassium: "పొటాషియం",
    organicCarbon: "సేంద్రీయ కార్బన్",
    texture: "ఆకృతి",
    recommendation: "మీకు ఉత్తమ పంట",
    whyThisCrop: "ఈ పంట ఎందుకు?",
    acidic: "ఆమ్ల",
    neutral: "తటస్థ",
    alkaline: "క్షార",
    low: "తక్కువ",
    medium: "మధ్యస్థ",
    high: "అధిక",
    sandy: "ఇసుక",
    loamy: "ఒండ్రు",
    clay: "బంకమట్టి",
    safeToSpray: "పిచికారీ చేయడం సురక్షితం",
    dontSpray: "పిచికారీ చేయవద్దు",
    rainWarning: "వర్షం పడే అవకాశం ఉంది. ఎరువులు కొట్టుకుపోతాయి.",
    windWarning: "బలమైన గాలి. పురుగుమందు వృధా అవుతుంది.",
    perfectDay: "వ్యవసాయ పనులకు అనుకూలమైన రోజు.",
    eligibleSchemes: "అర్హత కలిగిన పథకాలు",
    checkEligibility: "అర్హతను తనిఖీ చేస్తోంది...",
    soilStatus: "నేల స్థితి",
    healthy: "ఆరోగ్యకరమైనది",
    needsCare: "శ్రద్ధ అవసరం",
    fertilizerAdvice: "ఎరువుల సలహా",
    tips: "ముఖ్యమైన చిట్కాలు",
    reduceNitrogen: "యూరియాను తగ్గించండి.",
    addPotash: "పొటాష్ జోడించండి.",
    addPhosphorus: "ఫాస్పరస్ జోడించండి.",
    addCompost: "సేంద్రీయ ఎరువులు వేయండి.",
    waterFreq: "ఇసుక నేలకు తరచుగా నీరు పెట్టాలి.",
    drainage: "మురుగునీటి పారుదల ఉండేలా చూసుకోండి.",
    soilSummary: "మీ నేల",
    is: "ఉంది",
    and: "మరియు",
    marketPrice: "మార్కెట్ ధర",
    sellNow: "ఇప్పుడే అమ్మండి",
    wait: "వేచి ఉండండి",
    farmHistory: "వ్యవసాయ రికార్డు పుస్తకం",
    pastRecords: "గత పంట రికార్డులు",
    profit: "లాభం",
    loss: "నష్టం",
    aiInsight: "AI అంతర్దృష్టి",
    historyWarning: "గతసారి, ఈ పంటకు వ్యాధి సమస్యలు వచ్చాయి.",
    preventiveAction: "ఈ సీజన్‌లో ముందుగానే నివారణ చర్యలు తీసుకోండి.",
    priceUp: "గత వారం కంటే ధర ఎక్కువగా ఉంది.",
    priceDown: "ఇటీవల ధర తగ్గింది.",
    cropGrowth: "పంట పెరుగుదల",
    currentStage: "ప్రస్తుత దశ",
    cropAge: "పంట వయస్సు",
    days: "రోజులు",
    financialAdvice: "ఖర్చు సలహా",
    invested: "పెట్టుబడి",
    risk: "ప్రమాదం",
    myCropStatus: "నా పంట స్థితి",
    seedling: "మొలక",
    vegetative: "పెరుగుదల",
    flowering: "పూత",
    fruiting: "కాత",
    harvest: "కోత",
    uploadReport: "మట్టి నివేదికను అప్‌లోడ్ చేయండి",
    govtCard: "Govt సాయిల్ హెల్త్ కార్డ్ పొందండి",
    analyzingReport: "మట్టి నివేదికను చదువుతోంది...",
    verified: "ల్యాబ్ రిపోర్ట్ ద్వారా ధృవీకరించబడింది",
    estimated: "ఉపగ్రహ అంచనా",
    getFreeTest: "ఉచిత మట్టి పరీక్ష పొందండి",
    govtShcHelp: "మట్టి నమూనాతో సమీపంలోని వ్యవసాయ కార్యాలయాన్ని సందర్శించండి. 14 రోజుల్లో రిపోర్ట్ పొందండి.",
    sustainable: "సుస్థిర వ్యవసాయం",
    mulching: "మల్చింగ్",
    cropRotation: "పంట మార్పిడి",
    waterMgmt: "నీటి నిర్వహణ",
    profile: "నా ప్రొఫైల్",
    logout: "లాగ్ అవుట్",
    help: "సహాయం",
    irrigation: "నీటిపారుదల రకం",
    soilType: "నేల రకం",
    farmingExp: "అనుభవం (సంవత్సరాలు)",
    tubeWell: "బోరు బావి",
    canal: "కాలువ",
    rainFed: "వర్షాధారం",
    drip: "బిందు సేద్యం",
    blackSoil: "నల్లరేగడి నేల",
    redSoil: "ఎర్ర నేల"
  },
  [Language.ML]: {
    welcome: "സ്വാഗതം",
    tapToSpeak: "സംസാരിക്കാൻ ടാപ്പ് ചെയ്യുക",
    register: "കർഷക രജിസ്ട്രേഷൻ",
    name: "മുഴുവൻ പേര്",
    phone: "മൊബൈൽ നമ്പർ",
    location: "ഗ്രാമം / ജില്ല",
    crop: "പ്രധാന കൃഷി",
    acres: "കൃഷിസ്ഥലത്തിന്റെ വലിപ്പം (ഏക്കർ)",
    submit: "പ്രൊഫൈൽ സേവ് ചെയ്യുക",
    detect: "രോഗം കണ്ടെത്തൽ",
    weather: "കാലാവസ്ഥ & മുന്നറിയിപ്പുകൾ",
    yield: "വിളവ് പ്രവചനം",
    community: "കമ്മ്യൂണിറ്റി റിപ്പോർട്ടുകൾ",
    soilHealth: "മണ്ണിന്റെ ആരോഗ്യം",
    topCrop: "മികച്ച വിള",
    inputAdvisor: "ഇൻപുട്ട് ഉപദേഷ്ടാവ്",
    schemes: "സർക്കാർ പദ്ധതികൾ",
    alert: "മുന്നറിയിപ്പ്",
    safe: "സുരക്ഷിതം",
    loading: "ചിന്തിക്കുന്നു...",
    takePhoto: "ഫോട്ടോ എടുക്കുക / അപ്‌ലോഡ് ചെയ്യുക",
    analyzing: "ഇല പരിശോധിക്കുന്നു...",
    treatment: "ചികിത്സാ നിർദ്ദേശം",
    do: "ചെയ്യുക",
    dont: "ചെയ്യരുത്",
    share: "കമ്മ്യൂണിറ്റിയുമായി പങ്കിടുക",
    shared: "റിപ്പോർട്ട് പങ്കിട്ടു",
    voiceFallback: "ദയവായി നിങ്ങളുടെ വിവരങ്ങൾ ടൈപ്പ് ചെയ്യുക.",
    yieldCalc: "വിളവ് കണക്കാക്കുക",
    factors: "പ്രധാന ഘടകങ്ങൾ",
    soilAnalysis: "മണ്ണ് പരിശോധന",
    phLevel: "pH നില",
    nitrogen: "നൈട്രജൻ",
    phosphorus: "ഫോസ്ഫറസ്",
    potassium: "പൊട്ടാസ്യം",
    organicCarbon: "ജൈവ കാർബൺ",
    texture: "ഘടന",
    recommendation: "നിങ്ങൾക്ക് അനുയോജ്യമായ വിള",
    whyThisCrop: "എന്തുകൊണ്ട് ഈ വിള?",
    acidic: "അസിഡിക്",
    neutral: "ന്യൂട്രൽ",
    alkaline: "ആൽക്കലൈൻ",
    low: "കുറവ്",
    medium: "ഇടത്തരം",
    high: "കൂടുതൽ",
    sandy: "മണൽ",
    loamy: "എക്കൽ",
    clay: "കളിമണ്ണ്",
    safeToSpray: "സ്പ്രേ ചെയ്യാൻ സുരക്ഷിതമാണ്",
    dontSpray: "സ്പ്രേ ചെയ്യരുത്",
    rainWarning: "മഴ പ്രതീക്ഷിക്കുന്നു. വളം ഒലിച്ചുപോകും.",
    windWarning: "ശക്തമായ കാറ്റ്. കീടനാശിനി നഷ്ടപ്പെടും.",
    perfectDay: "കൃഷിക്ക് അനുയോജ്യമായ ദിവസം.",
    eligibleSchemes: "അർഹമായ പദ്ധതികൾ",
    checkEligibility: "യോഗ്യത പരിശോധിക്കുന്നു...",
    soilStatus: "മണ്ണിന്റെ അവസ്ഥ",
    healthy: "ആരോഗ്യമുള്ളത്",
    needsCare: "ശ്രദ്ധ ആവശ്യമാണ്",
    fertilizerAdvice: "വളപ്രയോഗ നിർദ്ദേശം",
    tips: "പ്രധാന നിർദ്ദേശങ്ങൾ",
    reduceNitrogen: "യൂറിയ കുറയ്ക്കുക.",
    addPotash: "പൊട്ടാഷ് ചേർക്കുക.",
    addPhosphorus: "ഫോസ്ഫറസ് ചേർക്കുക.",
    addCompost: "ജൈവവളം ചേർക്കുക.",
    waterFreq: "മണൽ മണ്ണിന് ഇടയ്ക്കിടെ നനയ്ക്കണം.",
    drainage: "നീർവാർച്ച ഉറപ്പാക്കുക.",
    soilSummary: "നിങ്ങളുടെ മണ്ണ്",
    is: "ആണ്",
    and: "കൂടാതെ",
    marketPrice: "വിപണി വില",
    sellNow: "ഇപ്പോൾ വിൽക്കുക",
    wait: "കാത്തിരിക്കുക",
    farmHistory: "ഫാം റെക്കോർഡ് ബുക്ക്",
    pastRecords: "കഴിഞ്ഞ വിള രേഖകൾ",
    profit: "ലാഭം",
    loss: "നഷ്ടം",
    aiInsight: "AI ഇൻസൈറ്റ്",
    historyWarning: "കഴിഞ്ഞ തവണ ഈ വിളയ്ക്ക് രോഗബാധയുണ്ടായിരുന്നു.",
    preventiveAction: "ഈ സീസണിൽ നേരത്തെ തന്നെ പ്രതിരോധ നടപടികൾ സ്വീകരിക്കുക.",
    priceUp: "കഴിഞ്ഞ ആഴ്ചയേക്കാൾ വില കൂടുതലാണ്.",
    priceDown: "അടുത്തിടെ വില ഇടിഞ്ഞു.",
    cropGrowth: "വിള വളർച്ച",
    currentStage: "നിലവിലെ ഘട്ടം",
    cropAge: "വിളയുടെ പ്രായം",
    days: "ദിവസങ്ങൾ",
    financialAdvice: "ചെലവ് ഉപദേശം",
    invested: "നിക്ഷേപിച്ചു",
    risk: "റിസ്ക്",
    myCropStatus: "എന്റെ വിള നില",
    seedling: "തൈ",
    vegetative: "വളർച്ച",
    flowering: "പൂവിടൽ",
    fruiting: "കായ്ക്കൽ",
    harvest: "വിളവെടുപ്പ്",
    uploadReport: "മണ്ണ് റിപ്പോർട്ട് അപ്‌ലോഡ് ചെയ്യുക",
    govtCard: "സർക്കാർ സോയിൽ ഹെൽത്ത് കാർഡ് നേടുക",
    analyzingReport: "മണ്ണ് റിപ്പോർട്ട് വായിക്കുന്നു...",
    verified: "ലാബ് റിപ്പോർട്ട് പരിശോധിച്ചു",
    estimated: "സാറ്റലൈറ്റ് എസ്റ്റിമേറ്റ്",
    getFreeTest: "സൗജന്യ മണ്ണ് പരിശോധന നേടുക",
    govtShcHelp: "മണ്ണിന്റെ സാമ്പിളുമായി അടുത്തുള്ള കൃഷി ഓഫീസിൽ സന്ദർശിക്കുക. 14 ദിവസത്തിനുള്ളിൽ റിപ്പോർട്ട് നേടുക.",
    sustainable: "സുസ്ഥിര കൃഷി",
    mulching: "പുതയിടൽ",
    cropRotation: "വിള പരിക്രമണം",
    waterMgmt: "ജല പരിപാലനം",
    profile: "എന്റെ പ്രൊഫൈൽ",
    logout: "ലോഗ് ഔട്ട്",
    help: "സഹായം",
    irrigation: "ജലസേചന തരം",
    soilType: "മണ്ണിന്റെ തരം",
    farmingExp: "പരിചയം (വർഷങ്ങൾ)",
    tubeWell: "കുഴൽക്കിണർ",
    canal: "കനാൽ",
    rainFed: "മഴവെള്ളം",
    drip: "തുള്ളിനന",
    blackSoil: "കരിമണ്ണ്",
    redSoil: "ചെമ്മണ്ണ്"
  },
  [Language.KN]: {
    welcome: "ಸ್ವಾಗತ",
    tapToSpeak: "ಮಾತನಾಡಲು ಟ್ಯಾಪ್ ಮಾಡಿ",
    register: "ರೈತ ನೋಂದಣಿ",
    name: "ಪೂರ್ಣ ಹೆಸರು",
    phone: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    location: "ಗ್ರಾಮ / ಜಿಲ್ಲೆ",
    crop: "ಪ್ರಮುಖ ಬೆಳೆ",
    acres: "ಜಮೀನಿನ ವಿಸ್ತೀರ್ಣ (ಎಕರೆ)",
    submit: "ಪ್ರೊಫೈಲ್ ಉಳಿಸಿ",
    detect: "ರೋಗ ಪತ್ತೆ",
    weather: "ಹವಾಮಾನ & ಎಚ್ಚರಿಕೆಗಳು",
    yield: "ಇಳುವರಿ ಮುನ್ಸೂಚನೆ",
    community: "ಸಮುದಾಯ ವರದಿಗಳು",
    soilHealth: "ಮಣ್ಣಿನ ಆರೋಗ್ಯ",
    topCrop: "ಅತ್ಯುತ್ತಮ ಬೆಳೆ",
    inputAdvisor: "ಇನ್ಪುಟ್ ಸಲಹೆಗಾರ",
    schemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    alert: "ಎಚ್ಚರಿಕೆ",
    safe: "ಸುರಕ್ಷಿತ",
    loading: "ಆಲೋಚಿಸುತ್ತಿದ್ದೇನೆ...",
    takePhoto: "ಫೋಟೋ ತೆಗೆಯಿರಿ / ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    analyzing: "ಎಲೆಯನ್ನು ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    treatment: "ಚಿಕಿತ್ಸೆ ಸಲಹೆ",
    do: "ಮಾಡಿ",
    dont: "ಮಾಡಬೇಡಿ",
    share: "ಸಮುದಾಯದೊಂದಿಗೆ ಹಂಚಿಕೊಳ್ಳಿ",
    shared: "ವರದಿ ಹಂಚಿಕೊಳ್ಳಲಾಗಿದೆ",
    voiceFallback: "ದಯವಿಟ್ಟು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಟೈಪ್ ಮಾಡಿ.",
    yieldCalc: "ಇಳುವರಿ ಲೆಕ್ಕಾಚಾರ",
    factors: "ಪ್ರಮುಖ ಅಂಶಗಳು",
    soilAnalysis: "ಮಣ್ಣು ವಿಶ್ಲೇಷಣೆ",
    phLevel: "pH ಮಟ್ಟ",
    nitrogen: "ಸಾರಜನಕ",
    phosphorus: "ರಂಜಕ",
    potassium: "ಪೊಟ್ಯಾಸಿಯಮ್",
    organicCarbon: "ಸಾವಯವ ಇಂಗಾಲ",
    texture: "ರಚನೆ",
    recommendation: "ನಿಮಗೆ ಅತ್ಯುತ್ತಮ ಬೆಳೆ",
    whyThisCrop: "ಏಕೆ ಈ ಬೆಳೆ?",
    acidic: "ಆಮ್ಲೀಯ",
    neutral: "ತಟಸ್ಥ",
    alkaline: "ಕ್ಷಾರೀಯ",
    low: "ಕಡಿಮೆ",
    medium: "ಮಧ್ಯಮ",
    high: "ಹೆಚ್ಚು",
    sandy: "ಮರಳು",
    loamy: "ಮೆಕ್ಕಲು",
    clay: "ಜೇಡಿಮಣ್ಣು",
    safeToSpray: "ಸಿಂಪಡಿಸಲು ಸುರಕ್ಷಿತ",
    dontSpray: "ಸಿಂಪಡಿಸಬೇಡಿ",
    rainWarning: "ಮಳೆ ನಿರೀಕ್ಷಿಸಲಾಗಿದೆ. ಗೊಬ್ಬರ ಕೊಚ್ಚಿಕೊಂಡು ಹೋಗುತ್ತದೆ.",
    windWarning: "ಬಲವಾದ ಗಾಳಿ. ಕೀಟನಾಶಕ ವ್ಯರ್ಥವಾಗುತ್ತದೆ.",
    perfectDay: "ಕೃಷಿ ಚಟುವಟಿಕೆಗಳಿಗೆ ಸೂಕ್ತವಾದ ದಿನ.",
    eligibleSchemes: "ಅರ್ಹ ಯೋಜನೆಗಳು",
    checkEligibility: "ಅರ್ಹತೆಯನ್ನು ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    soilStatus: "ಮಣ್ಣಿನ ಸ್ಥಿತಿ",
    healthy: "ಆರೋಗ್ಯಕರ",
    needsCare: "ಗಮನ ಬೇಕು",
    fertilizerAdvice: "ಗೊಬ್ಬರ ಸಲಹೆ",
    tips: "ಪ್ರಮುಖ ಸಲಹೆಗಳು",
    reduceNitrogen: "ಯೂರಿಯಾವನ್ನು ಕಡಿಮೆ ಮಾಡಿ.",
    addPotash: "ಪೊಟ್ಯಾಶ್ ಸೇರಿಸಿ.",
    addPhosphorus: "ರಂಜಕವನ್ನು ಸೇರಿಸಿ.",
    addCompost: "ಸಾವಯವ ಗೊಬ್ಬರ ಸೇರಿಸಿ.",
    waterFreq: "ಮರಳು ಮಣ್ಣಿಗೆ ಆಗಾಗ್ಗೆ ನೀರು ಬೇಕು.",
    drainage: "ಚರಂಡಿ ವ್ಯವಸ್ಥೆ ಮಾಡಿ.",
    soilSummary: "ನಿಮ್ಮ ಮಣ್ಣು",
    is: "ಇದೆ",
    and: "ಮತ್ತು",
    marketPrice: "ಮಾರುಕಟ್ಟೆ ಬೆಲೆ",
    sellNow: "ಈಗ ಮಾರಾಟ ಮಾಡಿ",
    wait: "ನಿರೀಕ್ಷಿಸಿ",
    farmHistory: "ಕೃಷಿ ದಾಖಲೆ ಪುಸ್ತಕ",
    pastRecords: "ಹಿಂದಿನ ಬೆಳೆ ದಾಖಲೆಗಳು",
    profit: "ಲಾಭ",
    loss: "ನಷ್ಟ",
    aiInsight: "AI ಒಳನೋಟ",
    historyWarning: "ಕಳೆದ ಬಾರಿ, ಈ ಬೆಳೆಗೆ ರೋಗದ ಸಮಸ್ಯೆ ಇತ್ತು.",
    preventiveAction: "ಈ ಋತುವಿನಲ್ಲಿ ಮೊದಲೇ ಮುನ್ನೆಚ್ಚರಿಕೆ ಕ್ರಮಗಳನ್ನು ತೆಗೆದುಕೊಳ್ಳಿ.",
    priceUp: "ಬೆಲೆ ಕಳೆದ ವಾರಕ್ಕಿಂತ ಹೆಚ್ಚಾಗಿದೆ.",
    priceDown: "ಇತ್ತೀಚೆಗೆ ಬೆಲೆ ಇಳಿದಿದೆ.",
    cropGrowth: "ಬೆಳೆ ಬೆಳವಣಿಗೆ",
    currentStage: "ಪ್ರಸ್ತುತ ಹಂತ",
    cropAge: "ಬೆಳೆ ವಯಸ್ಸು",
    days: "ದಿನಗಳು",
    financialAdvice: "ವೆಚ್ಚ ಸಲಹೆ",
    invested: "ಹೂಡಿಕೆ ಮಾಡಲಾಗಿದೆ",
    risk: "ಅಪಾಯ",
    myCropStatus: "ನನ್ನ ಬೆಳೆ ಸ್ಥಿತಿ",
    seedling: "ಸಸಿ",
    vegetative: "ಬೆಳವಣಿಗೆ",
    flowering: "ಹೂವು",
    fruiting: "ಹಣ್ಣು",
    harvest: "ಕೊಯ್ಲು",
    uploadReport: "ಮಣ್ಣಿನ ವರದಿಯನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    govtCard: "ಸರ್ಕಾರಿ ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾರ್ಡ್ ಪಡೆಯಿರಿ",
    analyzingReport: "ಮಣ್ಣಿನ ವರದಿಯನ್ನು ಓದಲಾಗುತ್ತಿದೆ...",
    verified: "ಲ್ಯಾಬ್ ವರದಿಯಿಂದ ಪರಿಶೀಲಿಸಲಾಗಿದೆ",
    estimated: "ಉಪಗ್ರಹ ಅಂದಾಜು",
    getFreeTest: "ಉಚಿತ ಮಣ್ಣು ಪರೀಕ್ಷೆ ಪಡೆಯಿರಿ",
    govtShcHelp: "ಮಣ್ಣಿನ ಮಾದರಿಯೊಂದಿಗೆ ಹತ್ತಿರದ ಕೃಷಿ ಕಚೇರಿಗೆ ಭೇಟಿ ನೀಡಿ. 14 ದಿನಗಳಲ್ಲಿ ವರದಿ ಪಡೆಯಿರಿ.",
    sustainable: "ಸುಸ್ಥಿರ ಕೃಷಿ",
    mulching: "ಹೊದಿಕೆ (Mulching)",
    cropRotation: "ಬೆಳೆ ಪರಿವರ್ತನೆ",
    waterMgmt: "ನೀರು ನಿರ್ವಹಣೆ",
    profile: "ನನ್ನ ಪ್ರೊಫೈಲ್",
    logout: "ಲಾಗ್ ಔಟ್",
    help: "ಸಹಾಯ",
    irrigation: "ನೀರಾವರಿ ಪ್ರಕಾರ",
    soilType: "ಮಣ್ಣಿನ ವಿಧ",
    farmingExp: "ಅನುಭವ (ವರ್ಷಗಳು)",
    tubeWell: "ಕೊಳವೆ ಬಾವಿ",
    canal: "ಕಾಲುವೆ",
    rainFed: "ಮಳೆಯಾಶ್ರಿತ",
    drip: "ಹನಿ ನೀರಾವರಿ",
    blackSoil: "ಕಪ್ಪು ಮಣ್ಣು",
    redSoil: "ಕೆಂಪು ಮಣ್ಣು"
  },
  [Language.MR]: {
    welcome: "स्वागत आहे",
    tapToSpeak: "बोलण्यासाठी टॅप करा",
    register: "शेतकरी नोंदणी",
    name: "पूर्ण नाव",
    phone: "मोबाईल नंबर",
    location: "गाव / जिल्हा",
    crop: "मुख्य पीक",
    acres: "शेताचा आकार (एकड़)",
    submit: "प्रोफाइल जतन करा",
    detect: "रोग निदान",
    weather: "हवामान आणि इशारे",
    yield: "उत्पन्न अंदाज",
    community: "समुदाय अहवाल",
    soilHealth: "मृदा आरोग्य",
    topCrop: "सर्वोत्तम पीक",
    inputAdvisor: "इनपुट सल्लागार",
    schemes: "सरकारी योजना",
    alert: "सतर्कता",
    safe: "सुरक्षित",
    loading: "विचार करत आहे...",
    takePhoto: "फोटो घ्या / अपलोड करा",
    analyzing: "पानाचे विश्लेषण करत आहे...",
    treatment: "उपचार सल्ला",
    do: "करा",
    dont: "करू नका",
    share: "समुदायासोबत शेअर करा",
    shared: "अहवाल शेअर केला",
    voiceFallback: "कृपया तुमची माहिती टाइप करा.",
    yieldCalc: "उत्पन्न गणना",
    factors: "मुख्य घटक",
    soilAnalysis: "मृदा विश्लेषण",
    phLevel: "pH पातळी",
    nitrogen: "नायट्रोजन",
    phosphorus: "फॉस्फरस",
    potassium: "पोटॅशियम",
    organicCarbon: "सेंद्रिय कार्बन",
    texture: "पोत",
    recommendation: "तुमच्यासाठी सर्वोत्तम पीक",
    whyThisCrop: "हे पीक का?",
    acidic: "आम्लधर्मी",
    neutral: "उदासीन",
    alkaline: "अल्कधर्मी",
    low: "कमी",
    medium: "मध्यम",
    high: "जास्त",
    sandy: "वालुकामय",
    loamy: "पोयटा",
    clay: "चिकनमाती",
    safeToSpray: "फवारणीसाठी सुरक्षित",
    dontSpray: "फवारणी करू नका",
    rainWarning: "पावसाची शक्यता आहे. खत वाहून जाईल.",
    windWarning: "सोसाट्याचा वारा. कीटकनाशक वाया जाईल.",
    perfectDay: "शेतीसाठी अनुकूल दिवस.",
    eligibleSchemes: "पात्र योजना",
    checkEligibility: "पात्रता तपासत आहे...",
    soilStatus: "मृदा स्थिती",
    healthy: "निरोगी",
    needsCare: "लक्ष देण्याची गरज",
    fertilizerAdvice: "खत सल्ला",
    tips: "महत्वाच्या टिप्स",
    reduceNitrogen: "युरिया कमी करा.",
    addPotash: "पोटॅश टाका.",
    addPhosphorus: "फॉस्फरस टाका.",
    addCompost: "सेंद्रिय खत टाका.",
    waterFreq: "वालुकामय जमिनीला वारंवार पाणी लागते.",
    drainage: "पाण्याचा निचरा करा.",
    soilSummary: "तुमची माती",
    is: "आहे",
    and: "आणि",
    marketPrice: "बाजारभाव",
    sellNow: "आता विक्री करा",
    wait: "वाट पहा",
    farmHistory: "शेत रेकॉर्ड बुक",
    pastRecords: "मागील पीक रेकॉर्ड",
    profit: "नफा",
    loss: "तोटा",
    aiInsight: "AI अंतर्दृष्टी",
    historyWarning: "गेल्या वेळी या पिकाला रोगाचा त्रास झाला होता.",
    preventiveAction: "या हंगामात लवकर प्रतिबंधात्मक उपाय करा.",
    priceUp: "किंमत गेल्या आठवड्यापेक्षा जास्त आहे.",
    priceDown: "अलीकडे भाव पडले आहेत.",
    cropGrowth: "पीक वाढ",
    currentStage: "सध्याचा टप्पा",
    cropAge: "पिकाचे वय",
    days: "दिवस",
    financialAdvice: "खर्च सल्ला",
    invested: "गुंतवणूक केली",
    risk: "जोखीम",
    myCropStatus: "माझ्या पिकाची स्थिती",
    seedling: "रोपे",
    vegetative: "वाढ",
    flowering: "फुलोरा",
    fruiting: "फळधारणा",
    harvest: "कापणी",
    uploadReport: "मृदा अहवाल अपलोड करा",
    govtCard: "शासकीय मृदा आरोग्य कार्ड मिळवा",
    analyzingReport: "मृदा अहवाल वाचत आहे...",
    verified: "लॅब रिपोर्टद्वारे सत्यापित",
    estimated: "उपग्रह अंदाज",
    getFreeTest: "मोफत माती परीक्षण मिळवा",
    govtShcHelp: "मातीच्या नमुन्यासह जवळच्या कृषी कार्यालयात भेट द्या. १४ दिवसात अहवाल मिळवा.",
    sustainable: "शाश्वत शेती",
    mulching: "आच्छादन (Mulching)",
    cropRotation: "पीक फेरपालट",
    waterMgmt: "पाणी व्यवस्थापन",
    profile: "माझे प्रोफाइल",
    logout: "लॉग आउट",
    help: "मदत",
    irrigation: "सिंचनाचा प्रकार",
    soilType: "मातीचा प्रकार",
    farmingExp: "अनुभव (वर्षे)",
    tubeWell: "कूपनलिका",
    canal: "कालवा",
    rainFed: "कोरडवाहू",
    drip: "ठिबक",
    blackSoil: "काळी माती",
    redSoil: "लाल माती"
  }
};